name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
  
jobs:
  check-updates:
    runs-on: macos-latest
    permissions:
      issues: write
      contents: write  # Need write access for releases
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: cachix/install-nix-action@v31
    
    - uses: cachix/cachix-action@v16
      with:
        name: turso
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    
    - run: nix develop .#
   
    - name: "Build debug"
      run: ./build.sh
    
    - name: "Build release"
      run: ./build.sh --release
    
    - name: Package artifacts
      run: |
        mkdir -p releases
        cd target
        for dir in */; do
          target_name=${dir%/}
          tar -czf ../releases/libsql-${target_name}.tar.gz -C "$dir" .
        done
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: releases/*.tar.gz
        generate_release_notes: true
